### ISSUE TITLE
Add Super Lawyers support

### ISSUE THREAD

**Issue by angelacevans** [imFORZA/wp-lawyer#4]
http://www.superlawyers.com/about/attorney_badge.html

**Comment by bhubbard** [comment]
superlawyers.com offers several different badges, so we will need to decide how to support it, multiple badges?
http://www.superlawyers.com/badges/lawyer/a3129c50-5cad-492e-8cc7-49b9c9c4a74f.html

**Comment by bhubbard** [comment]
Ok, so its all just HTML, so we need to let the user provide the superlawyers url page. From there we can create shortcodes for every type superlawyers badges. Something like:

`[wplawyer superlawyer='badgetype' lawyer="john-doe"]`
